require "genetics/tree"
require "genetics/population"
require "genetics/selection/tournament"
require "genetics/selection/versus_tournament"
require "genetics/selection/rank"
require "genetics/selection/segaran"